# Generated by Django 5.1.3 on 2025-04-09 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='contact_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt'])]),
        ),
    ]
